services:
  - type: web
    name: theraw
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && cp -r public .next/standalone/public && cp -r .next/static .next/standalone/.next/static
    startCommand: HOSTNAME=0.0.0.0 node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_ENDPOINT
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
